image: alpine/edge
secrets:
  - 69e3be6a-fe40-4dec-84ce-ba2e5e9a62a0
  - 6bd78cb1-fa09-49d6-b099-b0158f82aa6b
environment:
  REPO: ryzech.net
  GH_USER: ryzech
tasks:
  - write-ssh-config: |
      cat <<_FILE_ >> ~/.ssh/config
      Host github.com
        IdentityFile ~/.ssh/id_rsa
        IdentitiesOnly yes
        BatchMode yes
        StrictHostKeyChecking no
      _FILE_
  - push-to-github: |
      cd ~/"${REPO}"
      # remove remotes/origin/HEAD so we don't push it
      git remote set-head origin -d
      git remote add github "git@github.com:${GH_USER}/${REPO}.git"
      git push --prune github '+refs/remotes/origin/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
