image: alpine/edge
secrets:
  - 69e3be6a-fe40-4dec-84ce-ba2e5e9a62a0
sources:
  - git@git.sr.ht/~ryzechdev/ryzech.net
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      # This is for not having to cd into your <repo> for each task
      echo 'cd ryzech.net' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:ryzech/ryzech.net.git
